# Generated by Django 5.1.2 on 2024-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('quality', models.CharField(max_length=10)),
                ('downloaded_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('downloaded_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
